# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(789, 552)
        LoginDialog.setMinimumSize(QtCore.QSize(789, 552))
        LoginDialog.setMaximumSize(QtCore.QSize(789, 552))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        LoginDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:/Desktop/e2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginDialog.setWindowIcon(icon)
        self.username_label = QtWidgets.QLabel(LoginDialog)
        self.username_label.setGeometry(QtCore.QRect(240, 130, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.username_lineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.username_lineEdit.setGeometry(QtCore.QRect(332, 129, 191, 41))
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.passwd_label = QtWidgets.QLabel(LoginDialog)
        self.passwd_label.setGeometry(QtCore.QRect(240, 200, 71, 21))
        self.passwd_label.setObjectName("passwd_label")
        self.passwd_lineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.passwd_lineEdit.setGeometry(QtCore.QRect(330, 180, 191, 41))
        self.passwd_lineEdit.setObjectName("passwd_lineEdit")
        self.login_pushButton = QtWidgets.QPushButton(LoginDialog)
        self.login_pushButton.setGeometry(QtCore.QRect(250, 320, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.login_pushButton.setFont(font)
        self.login_pushButton.setStyleSheet("color: rgb(0, 255, 255);\n"
"font: 75 14pt \"Agency FB\";\n"
"font: 75 14pt \"Agency FB\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(170, 255, 255);\n"
"font: 75 14pt \"Agency FB\";")
        self.login_pushButton.setObjectName("login_pushButton")
        self.registr_pushButton = QtWidgets.QPushButton(LoginDialog)
        self.registr_pushButton.setGeometry(QtCore.QRect(410, 320, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.registr_pushButton.setFont(font)
        self.registr_pushButton.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.registr_pushButton.setObjectName("registr_pushButton")

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "登录"))
        self.username_label.setText(_translate("LoginDialog", "账 号："))
        self.passwd_label.setText(_translate("LoginDialog", "密 码："))
        self.login_pushButton.setText(_translate("LoginDialog", "登录"))
        self.registr_pushButton.setText(_translate("LoginDialog", "注册"))
