# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'marge.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 474)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(30, 5, 581, 41))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.default_path_radion = QtWidgets.QRadioButton(self.splitter)
        self.default_path_radion.setChecked(True)
        self.default_path_radion.setObjectName("default_path_radion")
        self.custom_path_radion = QtWidgets.QRadioButton(self.splitter)
        self.custom_path_radion.setObjectName("custom_path_radion")
        self.is_sort_checkbox = QtWidgets.QCheckBox(self.splitter)
        self.is_sort_checkbox.setObjectName("is_sort_checkbox")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 30, 591, 351))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.marg_btu = QtWidgets.QPushButton(self.widget)
        self.marg_btu.setObjectName("marg_btu")
        self.gridLayout_2.addWidget(self.marg_btu, 0, 0, 1, 1)
        self.sort_label = QtWidgets.QLabel(self.widget)
        self.sort_label.setEnabled(False)
        self.sort_label.setObjectName("sort_label")
        self.gridLayout_2.addWidget(self.sort_label, 0, 3, 1, 1)
        self.custom_btu = QtWidgets.QPushButton(self.widget)
        self.custom_btu.setEnabled(False)
        self.custom_btu.setObjectName("custom_btu")
        self.gridLayout_2.addWidget(self.custom_btu, 0, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 1, 0, 1, 5)
        self.col_names = QtWidgets.QComboBox(self.widget)
        self.col_names.setEnabled(False)
        self.col_names.setObjectName("col_names")
        self.gridLayout_2.addWidget(self.col_names, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", " "))
        self.default_path_radion.setText(_translate("MainWindow", "默认路径"))
        self.custom_path_radion.setText(_translate("MainWindow", "自定义路径"))
        self.is_sort_checkbox.setText(_translate("MainWindow", "是否排序"))
        self.groupBox_2.setTitle(_translate("MainWindow", " "))
        self.marg_btu.setText(_translate("MainWindow", "合并文件"))
        self.sort_label.setText(_translate("MainWindow", "排序列名："))
        self.custom_btu.setText(_translate("MainWindow", "自定义文件夹"))
